# site settings
title: olivialta
description: A blog about code and art

# change blogpost url format
collections:
  posts:
    output: true
    permalink: /blog/:title

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-sitemap

# exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - assets/scripts/*.ts
  - package.json
  - package-lock.json
  - tsconfig.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
